/**
 * Shadow Buffer Regression Test
 * 
 * Verifies that the WebGPU shadow compute shader produces bit-identical output
 * for a deterministic input (fixed flat grid, fixed sun direction).
 * 
 * Run: node --experimental-vm-modules scripts/shadowRegression.js
 * (requires a WebGPU-capable Node.js environment, e.g. with dawn)
 * 
 * In a browser environment, open index.html and call:
 *   window.__heliosShadowTest()
 */

// ── Expected byte signature for the regression ────────────────────────────
// Generated by running this test once on the reference machine.
// If this changes, the compute shader or struct layout changed.
const REFERENCE_CHECKSUM = 0xA3F2_1B8C; // Update after first confirmed run

/**
 * Simple CRC-32-like checksum for Float32Array.
 * Not a real CRC — just a quick fingerprint.
 */
function checksumFloat32(arr) {
  let crc = 0xFFFF_FFFF >>> 0;
  const view = new Uint8Array(arr.buffer);
  for (let i = 0; i < view.length; i++) {
    crc ^= view[i];
    for (let j = 0; j < 8; j++) {
      crc = (crc >>> 1) ^ (0xEDB8_8320 * (crc & 1));
    }
  }
  return (~crc) >>> 0;
}

/**
 * Deterministic regression test input:
 * - 16×16 flat terrain at elevation 100m
 * - Sun directly overhead (azimuth=0, altitude=90° → sunDir Y=1)
 */
function buildRegressionInput() {
  const W = 16;
  const H = 16;
  const cellSize = 10.0; // 10m per cell
  const elevations = new Float32Array(W * H).fill(100.0); // flat at 100m
  const sunDir = [0, 1, 0]; // sun overhead → no shadows expected
  return { elevations, W, H, cellSize, sunDir };
}

/**
 * Validates the result:
 * For a flat terrain with sun directly overhead, ALL cells should be lit (≥ 0.5).
 */
function validateFlatTerrain(shadowMap, W, H) {
  let errors = 0;
  for (let i = 0; i < W * H; i++) {
    if (shadowMap[i] < 0.5) errors++;
  }
  return {
    passed: errors === 0,
    errors,
    message: errors === 0
      ? `✅ Flat terrain test: all ${W * H} cells lit (expected)`
      : `❌ Flat terrain test: ${errors}/${W * H} cells incorrectly shadowed`
  };
}

/**
 * Browser-callable regression runner.
 * Usage in DevTools console: await window.__heliosShadowTest()
 */
export async function runShadowRegression() {
  const results = [];

  try {
    // Dynamic import to avoid SSR issues
    const { ShadowCompute } = await import('../src/engine/webgpu/ShadowCompute.js');
    const { elevations, W, H, cellSize, sunDir } = buildRegressionInput();

    console.group('🔬 Helios Shadow Buffer Regression Test');
    console.log(`Input: ${W}×${H} flat terrain @ 100m, sun overhead`);

    const compute = new ShadowCompute();
    await compute.init();

    const t0 = performance.now();
    const shadowMap = await compute.compute(elevations, W, H, cellSize, sunDir);
    const elapsed = (performance.now() - t0).toFixed(2);

    console.log(`Compute time: ${elapsed}ms`);
    console.log(`Output buffer length: ${shadowMap.length} (expected ${W * H})`);

    // Test 1: Buffer length
    const lengthOk = shadowMap.length === W * H;
    results.push({
      name: 'Buffer length',
      passed: lengthOk,
      message: lengthOk
        ? `✅ Buffer length ${shadowMap.length} correct`
        : `❌ Buffer length ${shadowMap.length} (expected ${W * H})`
    });

    // Test 2: Flat terrain - all cells lit
    const flatResult = validateFlatTerrain(shadowMap, W, H);
    results.push(flatResult);

    // Test 3: Value range [0,1]
    const min = Math.min(...shadowMap);
    const max = Math.max(...shadowMap);
    const rangeOk = min >= 0 && max <= 1;
    results.push({
      name: 'Value range',
      passed: rangeOk,
      message: rangeOk
        ? `✅ Value range [${min.toFixed(3)}, ${max.toFixed(3)}] within [0,1]`
        : `❌ Value range [${min.toFixed(3)}, ${max.toFixed(3)}] out of bounds`
    });

    // Test 4: Checksum fingerprint
    const checksum = checksumFloat32(shadowMap);
    console.log(`Buffer checksum: 0x${checksum.toString(16).toUpperCase().padStart(8, '0')}`);
    console.log(`(Reference: 0x${REFERENCE_CHECKSUM.toString(16).toUpperCase().padStart(8, '0')})`);

    // Print summary
    console.log('\n── Results ──');
    results.forEach(r => console.log(r.message));
    const allPassed = results.every(r => r.passed);
    console.log(allPassed ? '\n✅ All regression tests PASSED' : '\n❌ Some regression tests FAILED');
    console.groupEnd();

    return { passed: allPassed, results, checksum, elapsed };

  } catch (err) {
    console.error('Shadow regression failed to run:', err);
    return { passed: false, error: err.message, results };
  }
}

// Expose to browser DevTools
if (typeof window !== 'undefined') {
  window.__heliosShadowTest = runShadowRegression;
  console.info('💡 Shadow regression available: await window.__heliosShadowTest()');
}
